from enum import StrEnum


class EventType(StrEnum):
    DEMAND_CREATED = "DEMAND_CREATED"
    DEMAND_FULFILLED = "DEMAND_FULFILLED"
    STOCKOUT = "STOCKOUT"
    BACKORDER_CREATED = "BACKORDER_CREATED"
    BACKORDER_FULFILLED = "BACKORDER_FULFILLED"
    PURCHASE_ORDER_CREATED = "PURCHASE_ORDER_CREATED"
    SUPPLIER_DELAY = "SUPPLIER_DELAY"
    SHIPMENT_RECEIVED = "SHIPMENT_RECEIVED"
    INVENTORY_TRANSFER = "INVENTORY_TRANSFER"
    HOLDING_COST = "HOLDING_COST"
