from enum import StrEnum


class EventType(StrEnum):
    DEMAND_CREATED = "DEMAND_CREATED"
    DEMAND_FULFILLED = "DEMAND_FULFILLED"
    STOCKOUT = "STOCKOUT"
    BACKORDER_CREATED = "BACKORDER_CREATED"
    BACKORDER_FULFILLED = "BACKORDER_FULFILLED"
    PURCHASE_ORDER_CREATED = "PURCHASE_ORDER_CREATED"
    SUPPLIER_DELAY = "SUPPLIER_DELAY"
    SHIPMENT_RECEIVED = "SHIPMENT_RECEIVED"
    INVENTORY_TRANSFER = "INVENTORY_TRANSFER"
    INVENTORY_LOSS = "INVENTORY_LOSS"
    DEMAND_SPIKE = "DEMAND_SPIKE"
    WAREHOUSE_SHUTDOWN = "WAREHOUSE_SHUTDOWN"
    SUPPLIER_SHUTDOWN = "SUPPLIER_SHUTDOWN"
    CAPACITY_REDUCTION = "CAPACITY_REDUCTION"
    LEAD_TIME_INCREASE = "LEAD_TIME_INCREASE"
    TRANSPORTATION_DELAY = "TRANSPORTATION_DELAY"
    HOLDING_COST = "HOLDING_COST"


DEMAND_CREATED = EventType.DEMAND_CREATED.value
DEMAND_FULFILLED = EventType.DEMAND_FULFILLED.value
STOCKOUT = EventType.STOCKOUT.value
BACKORDER_CREATED = EventType.BACKORDER_CREATED.value
BACKORDER_FULFILLED = EventType.BACKORDER_FULFILLED.value
PURCHASE_ORDER_CREATED = EventType.PURCHASE_ORDER_CREATED.value
SUPPLIER_DELAY = EventType.SUPPLIER_DELAY.value
SHIPMENT_RECEIVED = EventType.SHIPMENT_RECEIVED.value
INVENTORY_TRANSFER = EventType.INVENTORY_TRANSFER.value
INVENTORY_LOSS = EventType.INVENTORY_LOSS.value
DEMAND_SPIKE = EventType.DEMAND_SPIKE.value
WAREHOUSE_SHUTDOWN = EventType.WAREHOUSE_SHUTDOWN.value
SUPPLIER_SHUTDOWN = EventType.SUPPLIER_SHUTDOWN.value
CAPACITY_REDUCTION = EventType.CAPACITY_REDUCTION.value
LEAD_TIME_INCREASE = EventType.LEAD_TIME_INCREASE.value
TRANSPORTATION_DELAY = EventType.TRANSPORTATION_DELAY.value
HOLDING_COST = EventType.HOLDING_COST.value
