from enum import StrEnum


class EventType(StrEnum):
    DEMAND_CREATED = "DEMAND_CREATED"
    DEMAND_FULFILLED = "DEMAND_FULFILLED"
    STOCKOUT = "STOCKOUT"
    BACKORDER_CREATED = "BACKORDER_CREATED"
    BACKORDER_FULFILLED = "BACKORDER_FULFILLED"
    PURCHASE_ORDER_CREATED = "PURCHASE_ORDER_CREATED"
    SUPPLIER_DELAY = "SUPPLIER_DELAY"
    SHIPMENT_RECEIVED = "SHIPMENT_RECEIVED"
    INVENTORY_TRANSFER = "INVENTORY_TRANSFER"
    HOLDING_COST = "HOLDING_COST"


DEMAND_CREATED = EventType.DEMAND_CREATED
DEMAND_FULFILLED = EventType.DEMAND_FULFILLED
STOCKOUT = EventType.STOCKOUT
BACKORDER_CREATED = EventType.BACKORDER_CREATED
BACKORDER_FULFILLED = EventType.BACKORDER_FULFILLED
PURCHASE_ORDER_CREATED = EventType.PURCHASE_ORDER_CREATED
SUPPLIER_DELAY = EventType.SUPPLIER_DELAY
SHIPMENT_RECEIVED = EventType.SHIPMENT_RECEIVED
INVENTORY_TRANSFER = EventType.INVENTORY_TRANSFER
HOLDING_COST = EventType.HOLDING_COST
